export const FETCH_ASSETS_LOCATIONS = 'FETCH_ASSETS_LOCATIONS';
export const FETCH_ASSETS_LIST = 'FETCH_ASSETS_LIST';
export const FETCH_ASSET_TYPE_LIST = 'FETCH_ASSET_TYPE_LIST';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';